# Install script for directory: C:/Users/amigo/source/repos/LMMS/lmms/plugins/LadspaEffect/tap

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/opt/mingw32")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_autopan.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_autopan.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_autopan.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_autopan.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_chorusflanger.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_chorusflanger.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_chorusflanger.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_chorusflanger.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_deesser.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_deesser.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_deesser.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_deesser.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_doubler.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_doubler.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_doubler.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_doubler.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_dynamics_m.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_dynamics_m.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_dynamics_m.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_dynamics_m.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_dynamics_st.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_dynamics_st.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_dynamics_st.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_dynamics_st.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_echo.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_echo.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_echo.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_echo.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_eq.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_eq.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_eq.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_eq.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_eqbw.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_eqbw.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_eqbw.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_eqbw.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_limiter.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_limiter.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_limiter.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_limiter.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_pinknoise.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_pinknoise.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_pinknoise.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_pinknoise.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_pitch.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_pitch.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_pitch.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_pitch.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_reflector.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_reflector.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_reflector.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_reflector.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_reverb.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_reverb.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_reverb.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_reverb.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_rotspeak.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_rotspeak.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_rotspeak.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_rotspeak.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_sigmoid.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_sigmoid.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_sigmoid.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_sigmoid.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_tremolo.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_tremolo.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_tremolo.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_tremolo.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_tubewarmth.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_tubewarmth.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_tubewarmth.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_tubewarmth.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Debug/tap_vibrato.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/Release/tap_vibrato.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/MinSizeRel/tap_vibrato.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/plugins/ladspa" TYPE MODULE FILES "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa/RelWithDebInfo/tap_vibrato.dll")
  endif()
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/LadspaEffect/tap/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
