# Install script for directory: C:/Users/amigo/source/repos/LMMS/lmms/plugins

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/opt/mingw32")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/audio_file_processor/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/kicker/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/triple_oscillator/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/Amplifier/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/BassBooster/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/bit_invader/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/Bitcrush/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/carlabase/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/carlapatchbay/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/carlarack/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/CrossoverEQ/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/Delay/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/DualFilter/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/dynamics_processor/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/Eq/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/Flanger/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/HydrogenImport/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ladspa_browser/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/LadspaEffect/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/lb302/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/MidiImport/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/MidiExport/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/MultitapEcho/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/monstro/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/nes/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/opl2/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/organic/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/papu/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/patman/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/peak_controller_effect/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/GigPlayer/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/ReverbSC/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/sf2_player/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/sfxr/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/sid/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/SpectrumAnalyzer/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/stereo_enhancer/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/stereo_matrix/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/stk/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/vestige/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/vst_base/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/VstEffect/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/watsyn/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/waveshaper/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/vibed/cmake_install.cmake")
  include("C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/zynaddsubfx/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "C:/Users/amigo/source/repos/LMMS/lmms/cmake/plugins/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
